build:
  ci:
    - ./gradlew build
    - docker build -t stimpert/shippable-demo .

jobs:
  - name: hello-world-job
    type: runSh
    steps:
    - IN: shippable-demo_runCI
    - TASK:
          script:
            - |
              sh ./deployment/run_build.sh
