build:
  ci:
    - ./gradlew build -x test
    - docker build -t stimpert/shippable-demo .

resources:
  - name: ci-resource
    type: params
    versionTemplate:
      params:
        KEY1: value

jobs:
  - name: shippable-demo_runCI
    type: runCI
    steps:
      - OUT: ci-resource

  - name: hello-world-job
    type: runSh
    steps:
    - IN: ci-resource
    - TASK:
          script:
            - |
              echo "HELLO WORLD from hello-world-job"

