build:
  ci:
    - ./gradlew build -x test
    - docker build -t stimpert/shippable-demo .

jobs:
  - name: hello-world-job
    type: runSh
    steps:
    - IN: shippable-demo_runCI
    - TASK:
          script:
            - |
              echo "HELLO WORLD from hello-world-job"
